/**
 * Turns the typed seed content into migrations/0002_seed.sql.
 * Run with: node scripts/gen-seed-sql.ts
 */
import { writeFileSync } from "node:fs";

import {
  SEED_ABOUT,
  SEED_CONTACT,
  SEED_CV,
  SEED_CV_GROUPS,
  SEED_EXHIBITIONS,
  SEED_SERIES,
  SEED_SETTINGS,
  SEED_WORKS,
} from "../src/lib/seed.ts";

const q = (value: string | null) =>
  value === null ? "NULL" : `'${value.replace(/'/g, "''")}'`;

const insert = (table: string, columns: string[], values: (string | number)[]) =>
  `INSERT INTO ${table} (${columns.join(", ")}) VALUES (${values.join(", ")});`;

const lines: string[] = [
  "-- Generated by scripts/gen-seed-sql.ts — do not edit by hand.",
  "",
];

for (const s of SEED_SERIES) {
  lines.push(
    insert(
      "series",
      [
        "id",
        "slug",
        "medium",
        "years",
        "sort_order",
        "title_tr",
        "title_en",
        "meta_tr",
        "meta_en",
        "note_tr",
        "note_en",
        "cover_work_id",
        "published",
      ],
      [
        q(s.id),
        q(s.slug),
        q(s.medium),
        q(s.years),
        s.order,
        q(s.title.tr),
        q(s.title.en),
        q(s.meta.tr),
        q(s.meta.en),
        q(s.note.tr),
        q(s.note.en),
        q(s.coverWorkId),
        s.published ? 1 : 0,
      ],
    ),
  );
}

lines.push("");

for (const w of SEED_WORKS) {
  lines.push(
    insert(
      "works",
      [
        "id",
        "slug",
        "medium",
        "series_id",
        "year",
        "sort_order",
        "title_tr",
        "title_en",
        "caption_tr",
        "caption_en",
        "note_tr",
        "note_en",
        "width",
        "height",
        "slot",
        "image_key",
        "published",
      ],
      [
        q(w.id),
        q(w.slug),
        q(w.medium),
        q(w.seriesId),
        q(w.year),
        w.order,
        q(w.title.tr),
        q(w.title.en),
        q(w.caption.tr),
        q(w.caption.en),
        q(w.note.tr),
        q(w.note.en),
        w.width,
        w.height,
        q(w.slot),
        q(w.imageKey),
        w.published ? 1 : 0,
      ],
    ),
  );
}

lines.push("");

for (const e of SEED_EXHIBITIONS) {
  lines.push(
    insert(
      "exhibitions",
      [
        "id",
        "year",
        "sort_order",
        "title_tr",
        "title_en",
        "venue_tr",
        "venue_en",
        "kind_tr",
        "kind_en",
        "note_tr",
        "note_en",
        "url",
        "image_key",
        "published",
      ],
      [
        q(e.id),
        q(e.year),
        e.order,
        q(e.title.tr),
        q(e.title.en),
        q(e.venue.tr),
        q(e.venue.en),
        q(e.kind.tr),
        q(e.kind.en),
        q(e.note.tr),
        q(e.note.en),
        q(e.url),
        q(e.imageKey),
        e.published ? 1 : 0,
      ],
    ),
  );
}

lines.push("");

for (const g of SEED_CV_GROUPS) {
  lines.push(
    insert(
      "cv_groups",
      ["id", "sort_order", "title_tr", "title_en", "published"],
      [q(g.id), g.order, q(g.title.tr), q(g.title.en), g.published ? 1 : 0],
    ),
  );
}

lines.push("");

for (const c of SEED_CV) {
  lines.push(
    insert(
      "cv_entries",
      [
        "id",
        "group_id",
        "year",
        "sort_order",
        "title_tr",
        "title_en",
        "kind",
        "url",
        "published",
      ],
      [
        q(c.id),
        q(c.groupId),
        q(c.year),
        c.order,
        q(c.title.tr),
        q(c.title.en),
        q(c.kind),
        q(c.url),
        c.published ? 1 : 0,
      ],
    ),
  );
}

lines.push("");
lines.push(
  `INSERT INTO pages (key, data) VALUES ('about', ${q(JSON.stringify(SEED_ABOUT))});`,
);
lines.push(
  `INSERT INTO pages (key, data) VALUES ('contact', ${q(JSON.stringify(SEED_CONTACT))});`,
);
lines.push(
  `INSERT INTO pages (key, data) VALUES ('settings', ${q(JSON.stringify(SEED_SETTINGS))});`,
);
lines.push("");

writeFileSync("migrations/0002_seed.sql", lines.join("\n"), "utf8");
console.log(
  `migrations/0002_seed.sql: ${SEED_SERIES.length} series, ${SEED_WORKS.length} works, ${SEED_EXHIBITIONS.length} exhibitions, ${SEED_CV_GROUPS.length} cv groups, ${SEED_CV.length} cv, 3 pages`,
);
